language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - cd tests/example3/
  - composer install
  - cd ../../

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --exclude full

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
